services:
  frontend-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile_frontend
    image: frontend-app:latest
    container_name: frontend-app
    depends_on:
      - backend-app
    ports:
      - "80:80"
      - "443:443"
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile_backend
    image: backend-app:latest
    container_name: backend-app
    environment:
      - MONGODB_HOST=mongodb-app
    depends_on:
      - mongodb-app
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ..
        target: /home/orbit
  mongodb-app:
    build:
      context: .
      dockerfile: Dockerfile_mongodb
    image: mongodb-app:latest
    container_name: mongodb-app
    ports:
      - "27017:27017"
    #volumes:
    #  - ./data:/data/db
  fileserver-app:
    build:
      context: .
      dockerfile: Dockerfile_apache
    image: apache-app:latest
    container_name: apache-app
    volumes:
      - type: bind
        # source: /datadrive/sftp_user/tm4j_solar
        source: ..
        target: /usr/local/apache2/htdocs/files      
    ports:
      - "8080:80"
      - "8443:443"