services:
#  frontend-app:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile_frontend
#    image: frontend-app:latest
#    container_name: frontend-app
#    depends_on:
#      - backend-app
#    ports:
#      - "80:80"
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile_backend
    image: backend-app:latest
    container_name: backend-app
    environment:
      - MONGODB_HOST=mongodb-app
    depends_on:
      - mongodb-app
    ports:
      - "5000:5000"
  mongodb-app:
    build:
      context: .
      dockerfile: Dockerfile_mongodb
    image: mongodb-app:latest
    container_name: mongodb-app
    ports:
      - "27017:27017"
    #volumes:
    #  - ./data:/data/db
