services:
  frontend-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile_frontend
    image: frontend-app:latest
    container_name: frontend-app
    depends_on:
      - backend-app
    ports:
      - "80:80"
      - "443:443"
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile_backend
    image: backend-app:latest
    container_name: backend-app
    env_file:
      - ../env/.env
    environment:
      - MONGODB_HOST=mongodb-app
      - GITHUB_API_URL=${GITHUB_API_URL}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - mongodb-app
    ports:
      - "5000:5000"
    volumes:
      - ../:/home/orbit
      - ../backend/tmp/db/sqlite:/data/sqlite
      # - /datadrive/sftp_user/tm4j_solar/RUNNER:/data
  mongodb-app:
    build:
      context: .
      dockerfile: Dockerfile_mongodb
    image: mongodb-app:latest
    container_name: mongodb-app
    ports:
      - "27017:27017"
#    volumes:
#      - ../backend/tmp/db/mongodb:/data/db
  fileserver-app:
    build:
      context: .
      dockerfile: Dockerfile_apache
    image: apache-app:latest
    container_name: apache-app
    volumes:
        # - /datadrive/sftp_user/tm4j_solar:/usr/local/apache2/htdocs/files
        - ../:/usr/local/apache2/htdocs/files
    ports:
      - "8080:80"
      - "8443:443"
    